POST http://localhost:5000/api/getOffensiveWords HTTP/1.1
content-type: application/json

{
    "word": "מניאק"
}

###

GET  http://localhost:5000/api/getOffensiveWords HTTP/1.1
content-type: application/json

###

DELETE http://localhost:5000/api/getOffensiveWords HTTP/1.1
content-type: application/json

{
    "word": "להוסיף"
}